# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_symbol',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
